#!/usr/bin/env python3
"""Draft-pool hygiene audit over data/cards/*.json (M3 pool hygiene task).

Audits the DRAFTABLE pool (skills that CardReward.eligible_pool can offer:
card_kind == "skill", not signature, not innate, no upgrade_of) and flags:

  (a) class lines whose draftable count deviates >30% from the class mean
  (b) rarity-spread anomalies (a line with no draftable commons/uncommons/
      rares, or fewer than MIN_COMMONS commons -- commons are the 3-copy
      backbone of derived decks, ADR-0026)
  (c) crossover risks (ADR-0020): stat_mult >= 2.0 draftable below rare, or
      without a min_act at/after its crossover tier
      (2.0-2.4 -> act 7 / tier 3; 2.5-2.9 -> act 10 / tier 4; 3.0+ -> act 13)
  (d) 0-cost cards at common (3-copy) rarity -- free-economy stacking
  (e) descriptions that do not match their numbers ("Deal N", "Gain N Block",
      "Apply N Status", stat_mult percentages, sub-1.0 stat_mult without a
      "reduced stat scaling" note, empty descriptions)

Usage:  python3 tools/pool_audit.py [data/cards]
Exit 0 = clean, 1 = flags found. Read-only; fixes are authored by hand.
"""

import collections
import json
import re
import sys
from pathlib import Path

MIN_COMMONS = 5          # commons floor per class line (3-copy backbone)
DEVIATION = 0.30         # flag threshold vs the class-line mean
# Accepted (d) exceptions, each with a recorded rationale
# (docs/progress/2026-06-10-pool-hygiene.md): reported as watches, not flags.
ZERO_COST_COMMON_OK = {
    # flat neutral filler -- neutral cards never stat-scale (ADR-0016), so a
    # free 3-block / 2-damage play is honest chaff, not an engine.
    "fleet_footwork",
    "rock_throw",
    # 0.5 stat_mult + Exhaust (the guardrail is on the card); also the token
    # generated by spell_weave/arcane_dodge, and the charmer commons floor
    # needs it (commons >= 5).
    "magic_missile",
}
RARITIES = ("common", "uncommon", "rare")
# ADR-0020 crossover gates: stat_mult band -> earliest draftable act.
CROSSOVER_MIN_ACT = ((3.0, 13), (2.5, 10), (2.0, 7))
STAT = r"(?:STR|DEX|INT|Charm|Strength|Dexterity|Intelligence)"


def load_cards(cards_dir: Path) -> dict:
    cards = {}
    for path in sorted(cards_dir.glob("*.json")):
        data = json.loads(path.read_text())
        cards[data["id"]] = data
    return cards


def is_draftable(card: dict) -> bool:
    return (
        not card.get("upgrade_of")
        and not card.get("signature")
        and not card.get("innate")
        and card.get("card_kind", "skill") == "skill"
    )


def max_stat_mult(card: dict) -> float:
    return max(
        (e.get("stat_mult", 1.0) for e in card.get("effects", [])), default=1.0
    )


def required_min_act(mult: float) -> int:
    for threshold, act in CROSSOVER_MIN_ACT:
        if mult >= threshold:
            return act
    return 0


def check_description(card: dict) -> list:
    """Flag (e): numbers in the description vs the authored effects."""
    issues = []
    desc = card.get("description", "")
    effects = card.get("effects", [])
    if not desc.strip():
        return ["empty description"]
    neutral = card.get("character_tag", "neutral") == "neutral"
    dmg = [e for e in effects if e["type"] in ("damage", "pierce_damage")]
    blk = [e for e in effects if e["type"] in ("block", "self_block")]

    hybrid = re.search(r"Deal (\d+) \+ (\d+)% " + STAT, desc)
    pct = re.search(r"Deal (\d+)% " + STAT, desc)
    flat = re.search(r"Deal (\d+) damage", desc)
    if dmg:
        amount = dmg[0].get("amount", 0)
        mult = dmg[0].get("stat_mult", 1.0)
        if hybrid:
            if amount != int(hybrid.group(1)) or abs(mult - int(hybrid.group(2)) / 100) > 1e-6:
                issues.append(
                    "hybrid damage text %s+%s%% vs amount %s stat_mult %s"
                    % (hybrid.group(1), hybrid.group(2), amount, mult)
                )
        elif pct:
            if amount != 0 or abs(mult - int(pct.group(1)) / 100) > 1e-6:
                issues.append(
                    "%% damage text %s%% vs amount %s stat_mult %s"
                    % (pct.group(1), amount, mult)
                )
        elif flat:
            if amount != int(flat.group(1)):
                issues.append(
                    "damage text 'Deal %s' vs amount %s" % (flat.group(1), amount)
                )
            # A tagged card with sub-1.0 stat_mult must SAY so (the firecracker
            # convention); neutral cards never scale (ADR-0016), so a flat text
            # is honest there whatever the authored stat_mult.
            if (
                not neutral
                and abs(mult - 1.0) > 1e-6
                and "reduced stat scaling" not in desc
                and "high stat scaling" not in desc
            ):
                issues.append(
                    "flat damage text but stat_mult %s (needs a scaling note)" % mult
                )

    blk_hybrid = re.search(r"[Gg]ain (\d+) \+ (\d+)% DEX [Bb]lock", desc)
    blk_pct = re.search(r"[Gg]ain (\d+)% DEX [Bb]lock", desc)
    blk_flats = [int(m.group(1)) for m in re.finditer(r"gains? (\d+) [Bb]lock", desc)]
    if blk:
        amounts = [e.get("amount", 0) for e in blk]
        mult = blk[0].get("stat_mult", 1.0)
        if blk_hybrid:
            if amounts[0] != int(blk_hybrid.group(1)) or abs(mult - int(blk_hybrid.group(2)) / 100) > 1e-6:
                issues.append("hybrid block text vs amount %s stat_mult %s" % (amounts[0], mult))
        elif blk_pct:
            if amounts[0] != 0 or abs(mult - int(blk_pct.group(1)) / 100) > 1e-6:
                issues.append(
                    "%% block text %s%% vs amount %s stat_mult %s"
                    % (blk_pct.group(1), amounts[0], mult)
                )
        elif blk_flats:
            for n in blk_flats:
                if n not in amounts:
                    issues.append("block text '%s Block' vs amounts %s" % (n, amounts))
            if (
                not neutral
                and abs(mult - 1.0) > 1e-6
                and "reduced stat scaling" not in desc
                and "high stat scaling" not in desc
            ):
                issues.append(
                    "flat block text but stat_mult %s (needs a scaling note)" % mult
                )

    for m in re.finditer(r"[Aa]pply (\d+) (\w+)", desc):
        n, status = int(m.group(1)), m.group(2).lower()
        matching = [
            e for e in effects
            if e["type"] == "apply_status" and e.get("status", "").lower() == status
        ]
        if matching and not any(e.get("stacks") == n for e in matching):
            issues.append(
                "status text 'Apply %s %s' vs stacks %s"
                % (n, status, [e.get("stacks") for e in matching])
            )
    return issues


def main() -> int:
    cards_dir = Path(sys.argv[1] if len(sys.argv) > 1 else "data/cards")
    cards = load_cards(cards_dir)
    draftable = {cid: c for cid, c in cards.items() if is_draftable(c)}

    counts = collections.Counter()
    by_rarity = collections.defaultdict(collections.Counter)
    for c in draftable.values():
        tag = c.get("character_tag", "neutral")
        counts[tag] += 1
        by_rarity[tag][c.get("rarity", "common")] += 1

    print("== Draftable pool: class line x rarity ==")
    print("%-10s %7s %7s %9s %6s" % ("line", "total", "common", "uncommon", "rare"))
    for tag in sorted(counts):
        r = by_rarity[tag]
        print("%-10s %7d %7d %9d %6d"
              % (tag, counts[tag], r["common"], r["uncommon"], r["rare"]))
    print("total draftable: %d of %d cards\n" % (len(draftable), len(cards)))

    flags = []
    watches = []

    # (a) per-line deviation from the class mean (neutral shown, not averaged).
    # Over-mean is a flag (re-tag generics to neutral); under-mean is a WATCH --
    # it means missing content, which this audit cannot fix by re-raritying.
    classes = [t for t in counts if t != "neutral"]
    mean = sum(counts[t] for t in classes) / max(1, len(classes))
    print("class-line mean %.1f; +/-30%% band [%.1f, %.1f]"
          % (mean, mean * (1 - DEVIATION), mean * (1 + DEVIATION)))
    for tag in sorted(classes):
        dev = (counts[tag] - mean) / mean
        if dev > DEVIATION:
            flags.append("(a) %s pool %d deviates %+.0f%% from mean %.1f"
                         % (tag, counts[tag], dev * 100, mean))
        elif dev < -DEVIATION:
            watches.append("(a) %s pool %d is %+.0f%% vs mean %.1f -- content gap"
                           % (tag, counts[tag], dev * 100, mean))

    # (b) rarity-spread anomalies.
    for tag in sorted(counts):
        r = by_rarity[tag]
        if r["common"] < MIN_COMMONS:
            flags.append("(b) %s has %d draftable commons (< %d)"
                         % (tag, r["common"], MIN_COMMONS))
        for rarity in RARITIES:
            if r[rarity] == 0 and tag != "neutral":
                flags.append("(b) %s has NO draftable %s cards" % (tag, rarity))

    # (c) crossover gating (ADR-0020).
    for cid, c in sorted(draftable.items()):
        mult = max_stat_mult(c)
        if mult < 2.0:
            continue
        if c.get("rarity", "common") != "rare":
            flags.append("(c) %s: stat_mult %.1f below rare (%s)"
                         % (cid, mult, c.get("rarity")))
        need = required_min_act(mult)
        if c.get("min_act", 0) < need:
            flags.append("(c) %s: stat_mult %.1f needs min_act >= %d (has %s)"
                         % (cid, mult, need, c.get("min_act", 0)))

    # (d) 0-cost commons (3 derived-deck copies of a free play).
    for cid, c in sorted(draftable.items()):
        if c.get("energy_cost", 1) == 0 and c.get("rarity", "common") == "common":
            line = ("(d) %s (%s): 0-cost at common -- 3 free copies per deck"
                    % (cid, c.get("character_tag")))
            if cid in ZERO_COST_COMMON_OK:
                watches.append(line + " [allowlisted]")
            else:
                flags.append(line)

    # (e) description vs numbers -- across ALL cards (players read curses,
    # signatures and upgrades too), draftability marked for triage.
    for cid, c in sorted(cards.items()):
        for issue in check_description(c):
            flags.append("(e) %s [%s]: %s"
                         % (cid, "draft" if is_draftable(c) else "no-draft", issue))

    if watches:
        print("\n== WATCHES (%d, accepted/known -- no exit code) ==" % len(watches))
        for w in watches:
            print("  " + w)
    if flags:
        print("\n== FLAGS (%d) ==" % len(flags))
        for f in flags:
            print("  " + f)
        return 1
    print("\nNo flags. Pool is clean.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
